VERSION="2.2.1"

ACCOUNTS=["GB55IM3L726XLCFVUOWKJMQC7WU7ST2K6K5GCUKIRB6VLYZIGSSYRCUN"]

[DOCUMENTATION]
ORG_NAME="China Space"
ORG_URL="https://www.chinaspace-stellar.com/"
ORG_DESCRIPTION="The China National Space Administration is a government agency of the People's Republic of China headquartered in Haidian, Beijing, responsible for civil space administration and international space cooperation."
ORG_LOGO="https://www.chinaspace-stellar.com/cnsa.png"


[[CURRENCIES]]
code="CNSA"
status="live"
display_decimals=5
issuer="GB55IM3L726XLCFVUOWKJMQC7WU7ST2K6K5GCUKIRB6VLYZIGSSYRCUN"
anchor_asset_type="crypto"
name="China Space"
desc="The China National Space Administration is a government agency of the People's Republic of China headquartered in Haidian, Beijing, responsible for civil space administration and international space cooperation."
image="https://www.chinaspace-stellar.com/cnsa.png"
